#!/usr/bin/with-contenv bash
# Copyright (C) 2026 sognix
# SPDX-License-Identifier: AGPL-3.0-or-later

mkdir -p /videos/input /videos/output /batch /logs
chown abc:abc /videos /videos/input /videos/output /batch /logs
